Feat: P55, 59, 60, 61, 62 드론과 적 NPC의 HP와, NPC 죽음 구현
2024FALL-SWPP/team-project-for-2024-fall-swpp-team-14 pull request #16
Opened 2024-11-16 13:36 UTC by yebin1926

**백로그:**
- P55(드론 레이저 접촉 시 HP 감소), 
- P59(드론의 발사체와 접촉 시 NPC HP 감소와 HP가 0일 때 사라지게 됨), 
- P60(NPC 죽었을 때 죽음 이벤트 트리거와 특정 시간 이후로 개체 Destroy)
- P61(NPC 죽었을 때 파괴 효과음 추가)
- P62 (NPC 죽었을 때 음향효과 추가)
- NPC가 죽음 애니메이션을 하기 시작할 때 총에서 레이저가 나오지 않도록 수정

2024-11-16 14:07 UTC, ohajun12 commented
Navigator로서의 작업 내용은 별도로 구글 드라이브에 업로드했습니다.
- 링크 : https://drive.google.com/file/d/1JPRvf2wpE919MXQU_cSiiIm8YfEGLU7S/view
- 디자인 패턴
  - 전반적으로 간단한 작업들이라 현재는 주목할 만한 디자인 패턴은 사용되지 않았습니다.
- 개선 의견 제안
  - EnemyHealthManager.cs의 Update함수에서 hp가 0인지 매번 체크하는 과정은 비효율적일 수 있는데 enemyHp가 실제로 감소되는 경우에만 체크를 하는 방식은 어떨까요?
  - PatrolEnemyController.cs, StandingEnemyController.cs, WorkingEnemyController.cs에 공통되는 부분이 많은데 세 파일이 모두 EnemyController 클래스를 상속받거나 하는 식으로 현재 EnemyHealthController의 내용을 포함한 공통의 부모 클래스를 만들어 처리하는 것은 어떨까요?

2024-11-17 15:45 UTC, joon0615 commented
@yebin1926 PR13 머지 완료되었습니다. 해당 부분 최신화 진행 & Merge Conflict 없도록 조정 진행 부탁드립니다~

2024-11-18 00:18 UTC, joon0615 commented
지난 상호작용 관련 PR 때 제외되었던 NullReferenceException 처리 관련 커밋이 포함된 것으로 확인되어, @herry123435 @Caffeinus 두분도 리뷰어로 추가하겠습니다. + 개선의견 제안 1번 항목 반영되었고, main 브랜치 기준 최신화 진행도 확인하였습니다.

2024-11-18 00:25 UTC, joon0615 commented
* 테스트 결과 P55(드론 레이저 접촉 시 HP 감소), P59(드론의 발사체와 접촉 시 NPC HP 감소와 HP가 0일 때 사라지게 됨), P60(NPC 죽었을 때 죽음 이벤트 트리거와 특정 시간 이후로 개체 Destroy), P61(NPC 죽었을 때 파괴 효과음 추가). P62 (NPC 죽었을 때 음향효과 추가), NPC가 죽음 애니메이션을 하기 시작할 때 총에서 레이저가 나오지 않도록 수정 등은 확인하였습니다.
* 그러나, NullReferenceException은 발생하지 않지만, Collider 이슈로 드론이 맵의 땅바닥이나 건축물, 적NPC들을 모두 통과하는 오류가 발생합니다. 또한, 아직 사망하지 않은 적NPC의 경우에도 파티클 효과가 켜져 있는 경우가 종종 발생하였습니다. 
![image](https://github.com/user-attachments/assets/e127f185-7c6c-4c45-8dd3-9d08e026c238)

2024-11-18 01:51 UTC, ohajun12 requested changes
저도 현준님과 동일한 문제가 발생하는 것을 확인했습니다.
태스크들이 구현되어 있는 것은 확인했으나 드론이 벽들을 모두 통과하고, StandingEnemy를 제외한 적들에게 파티클 효과가 켜져 있는 오류가 발생했습니다.
또한 튜토리얼 맵에서 이전 PR의 변경사항이 적용되지 않는 것으로 보이는데 확인해주시면 감사하겠습니다

2024-11-18 07:09 UTC, joon0615 commented
정상 작동 확인되었습니다. 다만 2건의 오류를 제보드립니다. 
1. 로봇이 죽음 애니메이션을 수행할 때 벽을 뚫고 눕게 되는 현상이 존재합니다. 
2. 상호작용 진행 시 비밀번호를 잘못 입력한 경우, 이를 초기화하지 못하는 버그가 존재합니다. ESC를 눌러 탈출했을 경우, 상호작용 화면 재진입시 이전 입력 내용 초기화 진행 로직 추가하는 디버깅이 필요해보입니다. 

<br/>

우선 금번 건에 대해서는 Approve하고 관련 디버깅 태스크는, 기존에 NullReferenceException 핸들링을 위해 신설했던 백로그 넘버를 재활용하여 P132 Debugging - Robot Animation & Interaction Wrong Input로 다음 스프린트에서 처리하는 방향으로 계획 중입니다.

2024-11-18 07:10 UTC, joon0615 approved these changes

2024-11-18 07:11 UTC, ohajun12 commented
> 저도 현준님과 동일한 문제가 발생하는 것을 확인했습니다. 태스크들이 구현되어 있는 것은 확인했으나 드론이 벽들을 모두 통과하고, StandingEnemy를 제외한 적들에게 파티클 효과가 켜져 있는 오류가 발생했습니다. 또한 튜토리얼 맵에서 이전 PR의 변경사항이 적용되지 않는 것으로 보이는데 확인해주시면 감사하겠습니다

말씀드렸던 오류는 전부 수정되었음을 확인했습니다.
고생하셨습니다!

2024-11-18 07:11 UTC, ohajun12 approved these changes

2024-11-18 08:05 UTC, Caffeinus commented
P55(드론 레이저 접촉 시 HP 감소) : 고정형 레이저에 접촉 시 틱마다 HP가 감소하기로 했던 것 같은데 1회만 HP가 감소합니다. 이외(적 NPC 발사체)에는 정상 작동을 확인했습니다.
P59/60/61/62 : 문제 없이 작동함을 확인했습니다.
로봇이 죽음 애니메이션을 수행할 때 벽을 뚫고 눕게 되는 현상은 저도 로봇이 죽으며 공중에 뜨는 것 보다는 낫다고 생각합니다.

2024-11-18 08:06 UTC, Caffeinus approved these changes

2024-11-18 08:26 UTC, herry123435 approved these changes

2024-11-18 08:35 UTC, joon0615 commented
* P55번 도트 데미지 미구현 이슈: 다음 스프린트(스프린트3) 초기에 디버깅 관련 태스크를 신설하여 진행하겠습니다. 앞서 이야기 나온 애니메이션, 상호작용 인풋 초기화와 함께 한 태스크로 묶어 정의합니다. 
    * P132 - Debugging - Robot Animation & Interaction Wrong Input & Laser Dot Damage
* 1층 레이저가 있는 방에서 노트북이 있는 방으로 가는 문(서버 object들로 막혀 있는 것)의 collider가 문의 위쪽 부분에는 적용되어 있지 않은 이슈: 다음 스프린트(스프린트3) 후기에 기존에 마련된 메인 맵 수정 태스크 백로그(PR11 상의 버그 수정을 위한 객체 추가)에 해당 내용을 덧붙여 업데이트합니다. 
    * P133 - Main Map Fix (Adding objects to fix bug in PR11 + Object Collider Passthrough Bug in PR16)

<br/>

위와 같이 잔존 이슈 핸들링하기로 계획하고, 금번 PR은 마무리하겠습니다.

2024-11-18 08:36 UTC, merged